---
deployment:
  tasks:
    - export DEPLOYPATH=/home/usarhosting/public_html/
    - cd acm_website
    - npm install --production
    - npm run build
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production
